### PR TITLE
Setup REST api for project via django.

### PR DESCRIPTION
**Pull request by wocaldwell**
## Description
1. Name of Branch:
    wc-project-setup-1
2. Tickets related to PR (with links):
    [Project Setup](https://github.com/handy-pandas/bangazon_orientation_api/issues/5)
3. Feature/Fix Description:
    Initial setup of API framework following [this](http://www.django-rest-framework.org/tutorial/quickstart/) quickstart guide. What to expect: You should be able access the api when running a localhost:8000/bangazon/api/v1/ in your browser, you should see the api root.
4. What architectural changes made:
    Created entire app dataset with a root directory of `bangazon_orientation_api`.
5. Any dependency changes:
    Make sure the following are included in your environment:
```
pip install django
pip install djangorestframework
```
## Testing
1. New Unit Tests?
    None
2. All testing passes?
    N/A

## Documentation
1. Fully completed Documentation with signature?
     Yes, everything was imported; nothing authored.
2. Readme file updated?
     Yes
## Deployment
1. Any new migrations to run:
    Yes
`python manage.py migrate`

### CODE REVIEW

**Comment by taylorperkins** [comment]
Please be sure to add in some description of where I should go in the URL when running the server. Also, be sure to change the url path within urls.py to bangazon/api/v1

Otherwise, looks great!

**Comment by taylorperkins** [comment]
* bangazon/api/v1/

**Comment by taylorperkins** [comment]
moved the task back to backlog until fixes are made

**Comment by wocaldwell** [comment]
Made  those changes. Please test again.

**Comment by taylorperkins** [comment]
awesome man, looks great

**Pull request merged**
